apiVersion: v1
kind: Pod
metadata:
  name: capstone-deployment  
spec:
  containers:
  - name: capstone-app
    image: dtt2307/capstone-finalproject:latest
    ports:
    - containerPort: 80
