- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: $HOME
- name: Apply deployment configuration
  shell: "./bin/kubectl create -f {{ ENVIRONMENT_NAME }}-deployment.yaml"
  args:
    chdir: $HOME
