---
- name: "Install tar"
  shell: apt install tar
- name: "Get eksctl bin"
  shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  args:
    chdir: $HOME
- name: "Copy bin"
  shell: mv ./eksctl /usr/local/bin
