---
- name: "Create ekscluster"
  hosts: management
  user: ec2-user
  gather_facts: false
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"        
  tasks:
    - name: Check aws connection
      shell: aws iam list-users
    - name: Create EKS cluster
      shell: "eksctl create cluster --name eksctl-${ENVIRONMENT_NAME} --region=${AWS_DEFAULT_REGION}"
