- name: "Deploy latest app"
  hosts: management
  user: ec2-user
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Update the deployment to run the latest Build
      shell: "./bin/kubectl set image deployments/capstone-deployment capstone-app=dtt2307/latest"
      args:
        chdir: $HOME    
